#### CONFIGURATION SERVER ###
server.port=8080

####### DATABASE CONFIGURATION ########
spring.datasource.url=jdbc:postgresql://localhost:5432/opusfinancial
spring.datasource.username=dev_user
spring.datasource.password=dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

# HIKARI (Configuração mais leve para dev)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.test.database.replace=none

##### JWT TOKEN #####
api.security.token.secret=123456
