spring.application.name=opusfinancial
spring.profiles.active=dev

#### CONFIGURACAO SERVER ###
server.servlet.context-path=/opusfinancial
server.port=8080
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# COMPRESSION
server.compression.enabled=true
server.compression.min-response-size=1024

# FLYWAY
spring.flyway.enabled=false

# TOMCAT
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=100
server.tomcat.keep-alive-timeout=20s
server.tomcat.max-connections=10000

##### JWT TOKEN #####
api.security.token.secret=${JWT_TOKEN:123456}

#### AWS CONFIGURATION (Opus Custom) ####
opus.aws.region=${AWS_REGION:us-east-1}
opus.aws.credentials.access-key=${AWS_ACCESS_KEY:test}
opus.aws.credentials.secret-key=${AWS_SECRET_KEY:test}

# Endpoints (Separados para flexibilidade com LocalStack)
opus.aws.endpoints.sqs=${AWS_SQS_ENDPOINT:http://localhost:4566}
opus.aws.endpoints.sns=${AWS_SNS_ENDPOINT:http://localhost:4566}

# OpenAPI Configuration (SpringDoc)
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=br.com.systec.opusfinancial
springdoc.swagger-ui.enabled=false

# Scalar Configuration
scalar.path=/scalar